### ISSUE TITLE
edit() function doesn't open editing of newly created 

### ISSUE THREAD

**Issue by royharoush** [hluk/CopyQ#1985]
**Describe the bug**
I have a command that creates journal items. 
When I click CTRL+ALT+R it used to open a new item with predefined(auto generated) fields (time ,etc)
it useful when i want to record notes on the fly. 

this is the command 

```
copyq:
var window = str(data('application/x-copyq-owner-window-title'));
var tagsMime = 'application/x-copyq-tags';
var tags = str(data(tagsMime)) + ', ' + window; setData(tagsMime, tags);
var time = dateString('yyyy-MM-dd hh:mm:ss');
tab('Journal')
setData(mimeItemNotes, "Title: " + window + " | Time:" + time);
Command = insert(0,time +  " Journal" +" Changeme "   + tags);
edit(0);

```

the edit(0) command at the used to open the the item that was created for editing, now it doesnt. the item is still created, but it's not being opened for editing automatically. 

**To Reproduce**
1. import the command 
2. run the command.  (global shortcut or from the menu item) 
3. The item is created but copyq doesnt open the the item for editing. 

**Expected behavior**
using edit(0) in a command should open the the note that was created by previous commands for editing. 

**Version, OS and Environment**
windows 10
copyq version 4.1.0. 

**Additional context**
I love copyq !

**Comment by hluk** [comment]
Please update to the latest CopyQ version (v4.1.0 is very old).

**Comment by royharoush** [comment]
the newest versions have some very bad geometry issues on windows sadly :\ (when you drag and drop the copy window cross monitors). and they don't remember or check the right monitor your cursor is on when opening the window. 
I did check on 6.1.0 and it also happens there. 
the command i wrote should do what i think it should, right ?

**Comment by hluk** [comment]
> the newest versions have some very bad geometry issues on windows sadly :\ (when you drag and drop the copy window cross monitors). and they don't remember or check the right monitor your cursor is on when opening the window. I did check on 6.1.0 and it also happens there.

Oh, this should be fixed in development version. I did not have time to release new version yet.

You can try development version from here: https://ci.appveyor.com/project/hluk/copyq/builds/43550199/artifacts (I believe it is pretty much stable)

> the command i wrote should do what i think it should, right ?

The command works for me.

**Comment by royharoush** [comment]
i realized the problem. I had an external editor setup, and it tried to open it instead of opening inside copyq 
i think it's worth adding an option to edit() stating whether to edit in copyq or external editor 

the issues i mentioned (geometry and location and the cross monitoring movement) still exists in copyq-6.1.0.45 (from the nightly stable). I'll stick with 4.0.1.
Thank you :)!
