### ISSUE TITLE
Blacklist  to exclude selected applications

### ISSUE THREAD

**Issue by fade2gray** [hluk/CopyQ#216]
Would it be possible to add blacklist functionality in order to exclude selected applications from being monitored i.e. password managers etc.?

Thanks.

**Comment by quantenschaum** [comment]
This does not work for me, using Xubuntu 14.04, Copyq 2.4.0, KeePass 2.25.

The ignore command works, applied to other applications, but when I set the window title to "KeePass"  it does not work as expected.

 * It works when selecting an entry in KeePass, right click -> clipboard -> copy entries.
 * It does not work when copying username/password (ctrl-b/ctrl-c/double click) of an entry.

**Comment by hluk** [comment]
This works for me when copying from KeePassX. Can you try it with the [newest version](https://github.com/hluk/CopyQ/releases)?

**Comment by quantenschaum** [comment]
I am using KeePass, not KeePassX.

![image](https://cloud.githubusercontent.com/assets/3985599/6186858/ba44506a-b37f-11e4-8f13-5d728583eace.png)

**Comment by hluk** [comment]
You check if the window title is correctly recognized using following command (copy/paste to command list in Command dialog [F6]).

```
[Command]
Name=Show Window Title for Clipboard
Command="
    copyq:
    popup(\"Window Title\", data(\"application/x-copyq-owner-window-title\"), 4000)"
Automatic=true
Icon=\xf016
GlobalShortcut=DISABLED
```

Copy the content again and popup should show which window title the clipboard is from (you can copy the popup content with mouse right-click).

**Comment by quantenschaum** [comment]
(Cool, one can copy the command into the dialog.)

This is the problem: When copying username/password by double click, KeePass puts itself into background (minimizes) and the window title shown by copyq is the title of the (then) currently active window (not KeePass). 

If I disable the "drop to background after copy" option in KeePass, it works as expected.

Thank you.

**Comment by quantenschaum** [comment]
A comment on the clearing of the clipboard after a certain delay. What I observe is the following.

I setup copyq to ignore stuff copied from KeePass, but at the moment when KeePass clears the clipboard, the clipboard content is captured by copyq. I do not really understand why actually. copyq listens for clipboard changes and captures the new values, right? Now, when a password is copied to the clipboard from KeePass, then this is ignord. OK. But when now KeePass clears the clipboard, the new value shoud be "nothing", but copyq picks up the old content, the password. Why?

If the extend the ignore action command to

    copyq ignore
    sleep 10
    copyq copy
    copyq select 0

The I get an infinite loop, because

    copyq copy

does not set the clipboard content to something empty, but instead it issues a Ctrl+C, which copies what ever is currently selected and in focus. If this is an entry in KeePass, this goes on forever.

**Comment by hluk** [comment]
Well, the scripting functionality is powerful enough to break the app. I could try to add some guards so the instance that does the Ctrl+C will not run automatic commands on that new content -- on the other hand this could be bad if Ctrl+C is done on an active window is the one that should be ignored (with an automatic command).

I noticed that clipboard is kept even if the clipboard owner is closed or clipboard content reset (on X11). I'm not entirely sure why but this happens even if CopyQ is not running. I should be probably solved by checking in clipboard monitor if the clipboard content has really changed.

**Comment by hluk** [comment]
See: #319

**Comment by npluis** [comment]
The problem in (at least Linux) is that CopyQ sends a Crtl-C. So if I'm working on the commandline and copy a password from Keepass, it sends a ctrl-c after 10 seconds. 

I (may) have fixed it by using this command:

    copyq ignore
    sleep 10
    copyq copy('this is a test')
    copyq select 0

Not sure what kind of side effects it has but for now it seems to work in that it doesn't store my password in CopyQ and it doesn't send a ctrl-c to my GUI (command line)

**Comment by hluk** [comment]
Yes, `copyq copy` without further parameters invokes `Ctrl+C` in currently focused application. Command `copyq copy "TEXT"` copies "TEXT". to clipboard.

Funny thing is that running `copyq copy` in terminal interrupts the process (because that's what `Ctrl+C` usually does there).

Anyway, if window title filtering doesn't work, you can also check `copy clipboard "?"` if there are any interesting data formats which can be used to ignore the clipboard.

On Linux you also might need to filter mouse selections or disable storing items from selection in configuration dialog.

**Comment by roded** [comment]
I can't seem to get this working with KeePassXC on Linux.
Should the above be applicable now as well?

**Comment by hluk** [comment]
> I can't seem to get this working with KeePassXC on Linux.
> Should the above be applicable now as well?

I use following command so as CopyQ doesn't store stuff copied from KeePassXC.

```ini
[Command]
Automatic=true
Command="
    copyq ignore"
Icon=\xf069
Name=Ignore *\"Password\"* window
Remove=true
Window=" - KeePass"
```

**Comment by roded** [comment]
@hluk, thanks for the suggestion.
Though it seems that the command is ignored and passwords from KeepassXC are still copied into CopyQ. Not sure what I could be missing.

**Comment by hluk** [comment]
@roded How do you copy passwords from KeePassXC? Is ` - KeePass` part of the window title of the app?

**Comment by roded** [comment]
@hluk, disabling the "minimize on copy" option for KeePassXC solves the issue.
Is my understanding correct that there's no current solution to this for CopyQ?

**Comment by 0xorial** [comment]
Did anyone got this working with 1password popup window?

**Comment by hluk** [comment]
> disabling the "minimize on copy" option for KeePassXC solves the issue.
> Is my understanding correct that there's no current solution to this for CopyQ?

Except checking current window title, there is no other way CopyQ would know that the copied content is a secret and should be ignored.

> Did anyone get this working with 1password popup window?

I'm guessing, it's the same problem as with KeePassXC and minimizing the window after copying the password.

If you can figure out a regular expression matching your passwords, you can use following command.

```ini
[Command]
Automatic=true
Command="
    copyq notification \\
      .id password_notification \\
      .time 2000 \\
      .title 'Secret Copied'
Icon=\xf084
Input=text/plain
Match=^\\S*[a-zA-Z]+\\S*[0-9]+\\S*[a-zA-Z]+\\S*$
Name=Ignore Passwords and Secrets
Remove=true
```

It uses `^\S*[a-zA-Z]+\S*[0-9]+\S*[a-zA-Z]+\S*$` to match a series of non-whitespace characters with some digits in between bunch of letters. But obviously there could be false positives.

**Comment by stef204** [comment]
@hluk None of the above seems to work reliably.<br>
While copyq is excellent, the password issue (in combo with password managers such as the ones mentioned above) seems to create a security risk linked to the dat files containing the passwords. The dat files can be permissioned 600 but it still leaves the passwords in plain text inside those files which is not ideal.<br>
CopyQ needs a definitive solution to interact with the password manager's "clearing" of the clipboard after x seconds (for example)  in order to minimize this risk.

**Comment by fyanchev** [comment]
Hi, could not find the option to blacklist the Bitwarden firefox extension - is the blacklist option only available for apps and not for the said Firefox extension. 

Thank you for reply and time.

**Comment by hluk** [comment]
@fyanchev Maybe [this](https://github.com/hluk/CopyQ/issues/1194#issuecomment-521721647) can help? There is also #1068 with some ideas how to solve it. I'll try to update FAQ.

**Comment by Sukhman723** [comment]
@ hluk your mention solutions are not working at all. there is no clipboard entry i can see but i can see entry directly in copyq lists. I'm running sway (on archlinux) with no x server support. so is it causing any weird issues?

**Comment by hluk** [comment]
@Sukhman723 Getting window title on Wayland is not supported out of the box.

To get support for getting window title and other features on Sway Wayland compositor, you need to add a separate command [Sway and Wayland Support](https://github.com/hluk/copyq-commands/tree/master/Scripts#sway-and-wayland-support) (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command).

I also fixed the command in https://github.com/hluk/CopyQ/issues/216#issuecomment-418751058 (missing quote).

**Comment by Sukhman723** [comment]
@hluk that didn't worked. I tried that expression but i can still see my entries present in copyq tab. I just want copyq to ignore if i copy entries from KeePass. I already installed your specified packages by the way.

**Comment by hluk** [comment]
This is the command I'm using on Sway (with the [Sway and Wayland Support](https://github.com/hluk/copyq-commands/tree/master/Scripts#sway-and-wayland-support) command):

```ini
[Command]
Automatic=true
Command="
    copyq ignore"
Icon=\xf069
Name=Ignore *\"Password\"* window
Remove=true
Window=" - KeePass|Generate Password"
```

**Comment by Ten0** [comment]
I'm using the 1PasswordX extension and the process suggested in the FAQ to ignore "Password" window doesn't work, I suspect because that is an extension that doesn't affect the window's title.

**Comment by lnksz** [comment]
@hluk Thank you Lukas for the great support/maintenance, you rock sir!

**Comment by gabyx** [comment]
How can I find out the window name copyq is matching when copying, to check if my regex actually works?
Because `.*warden` for the bitwarden app on linux does not work apparently....

**Comment by hluk** [comment]
> How can I find out the window name copyq is matching when copying, to check if my regex actually works?

Try using [Show Window Title](https://github.com/hluk/copyq-commands/tree/master/Automatic#show-window-title) command (see [README.md](https://github.com/hluk/copyq-commands/blob/master/README.md) for details on how to add the command). With that the window title will show up in the new items created from clipboard.

**Comment by gabyx** [comment]
Ah just figured out that under Wayland does not work yet sadly (window titles is empty)
Is there any news on this? Any workarounds?

**Comment by hluk** [comment]
Not sure if there is something for other window managers or desktop environments, but current window title in **Sway** tiling window manager can be retrieved with:

```
swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.focused) | .name'
```

The command to ignore window ending with `warden` would be:

```ini
[Command]
Automatic=true
Command="
    swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.focused) | .name' | copyq:
    const regex = /warden$/
    const title = str(input()).trim();
    if (regex.test(title)) ignore()"
Icon=\xf05e
Name=Ignore Bitwarden
```

**Comment by gabyx** [comment]
Your my hero! Thanks alot! I use sway, for hyperland there is certainly a similar query with jq… Von meinem iPhone gesendetAm 08.11.2023 um 11:16 schrieb Lukas Holecek ***@***.***>:﻿
Not sure if there is something for other window managers or desktop environments, but current window title in Sway tiling window manager can be retrieved with:
swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.focused) | .name'

The command to ignore window ending with warden would be:
[Command]
Automatic=true
Command="
    swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.focused) | .name' | copyq:
    const regex = /warden$/
    const title = str(input()).trim();
    if (regex.test(title)) ignore()"
Icon=\xf05e
Name=Ignore Bitwarden

**Comment by Liassica** [comment]
The command
```sh
hyprctl clients -j | jq -r '. | (.? // empty)[] | select(.focusHistoryID | contains (0)) | .title' 
```
seems to do the equivalent for Hyprland. Hyprland keeps a "focus history", so this filters for the window with a focus history ID of 0, i.e. most recently focused.

**Comment by jdvgh** [comment]
I added the following as the first command: https://github.com/hluk/copyq-commands/blob/cb9ff28bd2370eba8849feb55d81102f0be77b47/Scripts/wayland-support.ini

and then afterwards:
```
[Command]
Automatic=true
Command=copyq ignore
Icon=*
Name=Ignore *\"Password\"* window
Remove=true
Window=.*warden.*
```
(using hyprland)
And it works for both bitwarden web and bitwarden client

**Comment by hluk** [comment]
CopyQ 8.0.0 ignores passwords in the clipboard out-of-the-box without any additional commands and settings if the password manager sets the clipboard properly to indicate a secret content. See #2500.

**Comment by MustCodeAl** [comment]
Is there an option to ignore wsl?
