### ISSUE TITLE
GUI misbehaves when "Disable Tray" setting is set

### ISSUE THREAD

**Issue by skycommand** [hluk/CopyQ#441]
Hi.
It appears CopyQ 2.6 and 2.5 GUI does not work properly when tray icon is disabled: The on-screen layout is not saved and sometimes CopyQ starts but I can't get to show its GUI. I end up killing it using task manager.

I start and exit CopyQ manually a lot and don't start it with Windows. I use it during office work or development work only.

**Comment by hluk** [comment]
What's the version of Windows?

It seems to behave correctly on Windows 8 and 7.

You can try deleting "%APPDATA%\copyq\copyq_geometry.ini" (configuration file with window geometries) or using "copyq showAt 0 0 300 300" command to show window with given geometry.

If you use commands in CopyQ you can try following one to show/hide main window with given geometry.

```ini
[Command]
Command="
    copyq:
    top = 0
    left = 0
    width = 300
    height = 300
    
    if (visible())
      hide()
    else
      showAt(top, left, width, height)"
GlobalShortcut=ctrl+shift+?
Icon=\xf022
Name=Show/hide with geometry
```

**Comment by skycommand** [comment]
I deleted copyq_geometry.ini. Now the window dimensions are always correct. But the window snaps to upper left corner. (0,0) Also the issue of the window not appearing at all is seemingly gone. So, thanks!

It is Windows 7 Professional x64, by the way. Oh, and I use the "Wine" theme.

**Comment by hluk** [comment]
Are you using the default command to show/hide main window? (The default is `copyq: toggle()`.)

**Comment by skycommand** [comment]
I am not even sure what "`copyq: toggle ()`" is. I use GUI. To show the window, I click on the task bar icon (formerly, on the tray icon). To hide the window, I close it via the X button.

**Comment by hluk** [comment]
Commands like the one above allows you to use custom keyboard shortcut to show main window or do lots of other things (if you're interested, [here](https://github.com/hluk/CopyQ/wiki/Writing-Commands-and-Adding-Functionality) is more info on that topic).

This makes it actually even stranger because the window geometry shouldn't be restored when closing the window (minimizing in case tray is disabled) or restoring the window.

**Comment by skycommand** [comment]
What _should_ happen?

**Comment by hluk** [comment]
If you move and resize the window the geometry is automatically saved. When you close or open it Windows should handle the window geometry that was restored at start of the application. Perhaps at some point while opening or closing the window the geometry changes momentarily and application saves some incorrect values -- but I can only guess since I cannot reproduce the issue.

**Comment by skycommand** [comment]
Here is a screencast of what happens: [CopyQ 2.6 launch issue](https://onedrive.live.com/redir?resid=EE0F5C6F873726F!1421&authkey=!AKXgkIcp7h97FG4&ithint=video%2cmp4) (.MP4, 13 MB, 1280×720)

**Comment by hluk** [comment]
OK, I just fixed it. The video is worth thousands words :). Thanks.

**Comment by skycommand** [comment]
Thank you! :)

**Comment by hluk** [comment]
You can try the portable version of CopyQ with the fix [here](https://ci.appveyor.com/api/buildjobs/hbl6fgejaqum1r49/artifacts/copyq.zip) -- the bundle is bigger since it's built with newer GUI library (hopefully you won't have any issues because of that).

**Comment by cecoutinho** [comment]
I've installed CopyQ in Ubuntu 17.10 and one annoying thing is that the "Disable tray" option does not do anything. The CopyQ icon is still shown on the list of applications even when I close its windows. Additionally I'd like to start it minimized i.e., at startup not showing the clip window and I can't seem to do that.

**Comment by hluk** [comment]
@cecoutinho That's probably another incompatibility issue with Wayland.

You should be able to completely hide the window by enabling "Hide main window" in "Layout" configuration tab - though you have to set a shortcut for showing main window (or set system shortcut to "copyq toggle").
