### ISSUE TITLE
Macos - links most of the time are not pasted

### ISSUE THREAD

**Issue by edevil** [hluk/CopyQ#724]
As the title says, I have problems pasting links (http://...). The rest of the content seems to work fine.

**Comment by hluk** [comment]
Can you provide steps to reproduce?

**Comment by scottkosty** [comment]
@edevil please always give the version of the software you're using when making issues. To see the CopyQ version, either use the command ```copyq --version``` or in the main menu go to Help > Help.

Links paste fine here on Ubuntu. Do you by chance have the "Ignore copied files" command active? If so and you are not using the newest version of CopyQ, you might have run into the issue fixed by 9b9e6104.

**Comment by edevil** [comment]
Version:
```
CopyQ Clipboard Manager v3.0.1 (hluk@email.cz)
Built with: Qt 5.8.0, LibQxt 0.7.0
```

When I copy the address bar of Chrome, for example, I can't paste it afterwards with CopyQ. Where is that "ignore copied files" option?

**Comment by scottkosty** [comment]
OK that version included the fix at 9b9e610 so my guess was wrong. You can see the The "ignore copied files" option in File > Commands/Global Shortcuts.

**Comment by hluk** [comment]
@edevil I cannot reproduce this with:

- CopyQ **v3.0.2**
- Google Chrome 59.0.3071.86 (Official Build) (64-bit)
- OS X Sierra 10.12.5

Steps:
1. select URL in Chrome with ⌘-L,
2. copy with ⌘-C,
3. open new tab with ⌘-T
4. open CopyQ window ([with global shortcut](https://copyq.readthedocs.io/en/latest/faq.html#how-to-open-application-window-or-tray-menu-using-shortcut)),
5. select the URL to paste ([pasting from main window needs to be enabled](https://copyq.readthedocs.io/en/latest/faq.html#how-to-paste-double-clicked-item-from-application-window)).

Definitely try to update CopyQ to the newest version.

**Comment by edevil** [comment]
I upgraded to 3.0.2 and can still reproduce this.

1. select URL in Chrome ⌘-L
1. copy ⌘-C
1. Change active window to iTerm2
1. Execute shortcut for "Show/hide main window"
1. Enter to select the last item (the URL)
1. Paste ⌘-V
1. Nothing happens

**Comment by edevil** [comment]
@scottkosty I can't find that option here.

![screen shot 2017-06-12 at 13 10 14](https://user-images.githubusercontent.com/12426/27033279-89774a66-4f70-11e7-9dbd-540af85f3a12.png)

**Comment by hluk** [comment]
@edevil Not sure why, but the plain text is ignored when clipboard contains URI list. To be able to paste to Terminal and iTerm2, these apps expect plain text to be in clipboard.

@rygwdn Does the plain text format need to be ignored when clipboard contains URI list? (See [this code comment](https://github.com/hluk/CopyQ/blob/016164170ababb5cc336bfaca67f1797142864bc/src/platform/mac/macclipboard.mm#L51-L55).)

**Comment by hluk** [comment]
@edevil You can use following command as workaround for now (Copy the code below and paste it in the Commands dialog <kbd>F6</kbd> with the "Paste Commands" button). This will store plain text if available with URI in **new items**.

```ini
[Command]
Automatic=true
Command="
    copyq:
    var text = clipboard(mimeText)
    if (text)
        setData(mimeText, text)"
Icon=\xf016
Input=text/uri-list
Name=Save URI with Text
```

**Comment by rygwdn** [comment]
That code could probably be made more specific so that it only discards the extra data for file URIs, or even just for URIs from Finder

**Comment by mohamed-osama-aboelkheir** [comment]
I am seeing the same issue on the below versions:
* MacOS 10.12.6
* CopyQ Clipboard Manager v3.1.2 (hluk@email.cz)
Built with: Qt 5.9.2, LibQxt 0.7.0
* Google chrome Version 64.0.3282.167 (Official Build) (64-bit)

Also, The issue is not occurring on Firefox 52.6.0 (64-bit)

Steps to reproduce:

1- Select a URL in chrome, and copy Cmd-C.
2- Show CopyQ menu.
3- Select another item.
4- Select back the url.
5- paste Cmd-V. nothing gets pasted.

Workaround:

The only workaround that worked for me is to run the below command, this creates a new version that works fine:

# copyq read | pbcopy

**Comment by reagle** [comment]
I can confirm this. I can paste URLs just copied, but once a URL is no longer top/recent, it will not paste.

<img width="620" alt="screen shot 2018-03-02 at 1 26 25 pm" src="https://user-images.githubusercontent.com/596814/36915105-84ed50d6-1e1d-11e8-862f-64906bdfa1ce.png">

For example, item 18. If I double click it (putting it at head of queue) and then paste somewhere, nothing! Same if I change the format. Been this way since sometime last year at least.

**Comment by hluk** [comment]
That's strange. I can only occasionally reproduce the problem. Sometimes only the `text/uri-list` item appears in the list without any `text/plain` format (sometimes both formats are there). Copying the item back to Chrome doesn't work - perhaps Chrome expects only `text/plain`.

**Comment by reagle** [comment]
It's not just chrome, I can't paste URIs that aren't recently-copied into *any* app.

**Comment by mohamed-osama-aboelkheir** [comment]
Yes, but this is only reproducible for me with urls copied from chrome into any applicaiton. If I copy url from firefox it works fine.

**Comment by scottkosty** [comment]
> Yes, but this is only reproducible for me with urls copied from chrome into any applicaiton. If I copy url from firefox it works fine.

What is the output when yo go to Item > Show Content, after copying from Chrome and from Firefox? Does one show text/uri-list and the other not?

**Comment by mohamed-osama-aboelkheir** [comment]
For chrome it is text/uri-list

<img width="566" alt="screen shot 2018-03-09 at 7 57 36 am" src="https://user-images.githubusercontent.com/7032838/37192716-b25c1190-236f-11e8-934d-68b0528abfa8.png">

For firefox it is text/plain

<img width="566" alt="screen shot 2018-03-09 at 7 59 43 am" src="https://user-images.githubusercontent.com/7032838/37192824-30ab4f52-2370-11e8-9a97-777b367f5df3.png">

After running the "copyq read | pbcopy" command I get a new entry of type text/plain

**Comment by mohamed-osama-aboelkheir** [comment]
Another observation, the type text/uri-list can only be pasted in chrome. Tried Terminal, iTerm2, Mocrosoft Word, another page but it can't be pasted on any of them.

**Comment by reagle** [comment]
Looking forward to trying this!

**Comment by reagle** [comment]
When's this likely to be released?

**Comment by hluk** [comment]
@reagle The fix should be already integrated in v3.3.1.

**Comment by reagle** [comment]
I'm running v3.3.1 and it seems to be working for Chrome. *However*, I still can't select older URLs from the copyq popup and paste them into iterm2 or sublime-text.

**Comment by hluk** [comment]
> However, I still can't select older URLs from the copyq popup and paste them into iterm2 or sublime-text

Yeah, the old items contain only `text/uri-list` and no `text/plain` so that won't work. You could let CopyQ always provide URL items as text with following command.

```ini
[Command]
Command="
    var provideClipboard_ = provideClipboard
    provideClipboard = function() {
        var uri = str(data(mimeUriList))
        if (uri) {
            var text = str(data(mimeText))
            if (!text)
                setData(mimeText, uri)
        }
        provideClipboard_()
    }"
Icon=\xf0c1
Input=text/uri-list
IsScript=true
Name=Always Copy URI as Text
```

**Comment by reagle** [comment]
If I can figure out how to do that, I'll give it a try. However, the current state of things is really unintuitive. Ordinary users aren't going to know about these different types and ill wonder why they can't perform the simple action of pasting a URL into their text editor or terminal. ( What is the URI - list type good for anyway?)

**Comment by reagle** [comment]
The suggested command is not working for me. After selecting the `automatic` checkbox so I can see what the command looks like, this is what I see:

<img width="865" alt="screen shot 2018-04-25 at 2 48 35 pm" src="https://user-images.githubusercontent.com/596814/39266379-dd2810fc-4897-11e8-999f-c7fe996071a3.png">

**Comment by hluk** [comment]
Well, any new items created by copying URL from Chrome should contain text - so the code above is not needed for those.

I don't want to add additional code to handle the old items.

URI lists can be useful when copying files from file managers (these won't handle plain text as paths).

**Comment by hluk** [comment]
> The suggested command is not working for me.

You need to use "Paste Commands" button in the Command dialog after copying the code ([here is how to add these commands to CopyQ](http://copyq.readthedocs.io/en/latest/faq.html#how-to-load-shared-commands-and-share-them)).

**Comment by reagle** [comment]
1. By old items, you mean legacy items in the clipboard before I updated to v3.3.1? I don't have any of those, I deleted the history for the purposes of testing.
2. I did the "Paste Commands" thing as instructed, but perhaps this is moot anyway since I'm not concerned with old items.

Here's the URL of this issue I just copied (using v3.3.1) and you can see it is being listed as text/uri-list.

<img width="641" alt="screen shot 2018-04-25 at 3 41 04 pm" src="https://user-images.githubusercontent.com/596814/39268916-2d58f454-489f-11e8-92c8-ddfbaa643b15.png">

It will not paste into iterm2 or sublime-text.

**Comment by hluk** [comment]
Oh, I think I misunderstood your first comment:

> I'm running v3.3.1 and it seems to be working for Chrome. However, I still can't select older URLs

So you can copy URL from Chrome and paste into terminal. But if the newly added item with the URL is copied, it cannot be pasted into terminal (presumably because the item still only contains `text/uri-list` format).

Is that correct?

What is the output of following command after you copy the link from Chrome?

```bash
copyq clipboard '?'
```

**Comment by reagle** [comment]
By "old" I mean any item that is not the most recent thing copied. URLs at the top of the stack paste, but once they are not the most recent, they don't.

Here's the types for the most recent/top item (a URL copied from Chrome):

```
application/x-copyq-uti-dyn.ah62d4rv4gu8zs3pcnzme2641rf4guzdmsv0gn64uqm10c6xenv61a3k
application/x-copyq-uti-dyn.ah62d4rv4gu8yc6durvwwaznwmuuha2pxsvw0e55bsmwca7d3sbwu
text/plain
text/uri-list
application/x-copyq-uti-public.url-name
```

Once I copy something else, and that URL moves down to a lower position, its types are:

```
public.utf16-plain-text
text/uri-list
application/x-copyq-owner
```

**Comment by hluk** [comment]
Not sure what's going on with the URI list format handling on OS X. I'm disabling storing it by default - only plain text will be stored instead. You can do this by going to **Preferences**, **Items tab**, select **Data** from the list and **remove "text/uri-list"** from the "Active formats" text window (or disable the Data plugin altogether).

**Comment by reagle** [comment]
@hluk, thanks for the suggestion. I've done that and paste seems to be working. I'm happy to test and future changes. BTW: Shouldn't this issue be open?

**Comment by hluk** [comment]
Glad it works for you.

> Shouldn't this issue be open?

If ignoring the URI format fixes this, then I would like to keep this close.

I'll add the solution to [FAQ](http://copyq.readthedocs.io/en/latest/faq.html).
